### ISSUE TITLE
Can't install on Ubuntu Bionic anymore

### ISSUE THREAD

**Issue by n1ngu** [weareinteractive/ansible-docker-compose#11]
Due to the new requirement on Rust due to the
```
cryptography <-- paramiko <-- docker[ssh] <-- docker-compose
```
dependency chain, this role requires the pip executable to be updated enough, which a new Ubuntu Bionic install won't satisfy.

Is anybody using this role on new machines? What are possible workarounds?

**Comment by n1ngu** [comment]
So far I am working around this by running
```
- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: latest
```
prior to this role. Then run this role with
```
- hosts: all
  roles:
    - weareinteractive.docker_compose
  vars:
    docker_compose_pip_executable: /usr/local/bin/pip3
```
